# src file
if(USE_GPU)
    message(STATUS "[device] use gpu")
    add_definitions(-DUSE_GPU)
#    target_compile_definitions(${PROJECT_NAME} PRIVATE USE_GPU)
#    list(APPEND SRC_DIR ${ROOT_DIR}/src/module/device/gpu)
elseif(NPU STREQUAL "aml")
    message(STATUS "[device] use amlogic npu")
    add_definitions(-DUSE_NPU_AML)
#    list(APPEND SRC_DIR ${ROOT_DIR}/src/module/device/npu_aml ${ROOT_DIR}/src/module/device/npu_aml/vnn)
elseif(NPU STREQUAL "rk")
    message(STATUS "[device] use rockchip npu")
    add_definitions(-DUSE_NPU_RK)
#    list(APPEND SRC_DIR ${ROOT_DIR}/src/module/device/npu_rk)
else()
    message("not set the device USE_GPU=ON or NPU=aml|rk, use cpu by default")
endif()

# lib
set(NPU_LIBRARIES -lOpenVX -lOpenVXU -lArchModelSw -lCLC -lGAL -lNNArchPerf -lVSC -lovxlib)

if (NPU STREQUAL "aml")
    set(AML_LIB /usr/share/npu/sdk/include/)
    message(STATUS "aml npu include: " ${AML_LIB})
    include_directories(${AML_LIB})
    set(CNN_LIBRARY ${NPU_LIBRARIES})
elseif(NPU STREQUAL "rk")
    message(STATUS "rockchip npu lib: ")
    set(CNN_LIBRARY -lrknnrt)
elseif(USE_GPU)
    set(MNN_LOW_MEMORY ON CACHE BOOL "Open MNN_LOW_MEMORY" FORCE)
    set(MNN_SUPPORT_TRANSFORMER_FUSE ON CACHE BOOL "Open MNN_SUPPORT_TRANSFORMER_FUSE" FORCE)
    set(MNN_BUILD_AUDIO ON CACHE BOOL "Open MNN_BUILD_AUDIO" FORCE)

    find_library(MNN_LIB NAMES MNN PATHS ${MNN_DIR}/lib REQUIRED)
    find_library(MNN_CUDA_MAIN NAMES MNN_Cuda_Main PATHS ${MNN_DIR}/lib REQUIRED)
    message(STATUS "gpu include: " ${MNN_DIR}/include ${MNN_DIR}/audio)
    include_directories(${MNN_DIR}/include)
    target_link_directories(${PROJECT_NAME} PRIVATE ${MNN_DIR}/lib)
    set(CNN_LIBRARY ${MNN_DIR}/lib/libMNN.so ${MNN_DIR}/lib/libMNN_Cuda_Main.so)
    #    set(CNN_LIBRARY MNN)
else () # use cpu
    set(MNN_LOW_MEMORY ON CACHE BOOL "Open MNN_LOW_MEMORY" FORCE)
    set(MNN_SUPPORT_TRANSFORMER_FUSE ON CACHE BOOL "Open MNN_SUPPORT_TRANSFORMER_FUSE" FORCE)
    set(MNN_BUILD_AUDIO ON CACHE BOOL "Open MNN_BUILD_AUDIO" FORCE)

    find_library(MNN_LIB NAMES MNN PATHS ${MNN_DIR}/lib REQUIRED)
    message(STATUS "gpu include: " ${MNN_DIR}/include ${MNN_DIR}/audio)
    include_directories(${MNN_DIR}/include)
    target_link_directories(${PROJECT_NAME} PRIVATE ${MNN_DIR}/lib)
    set(CNN_LIBRARY ${MNN_DIR}/lib/libMNN.so)
endif ()